name: Cypress Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md
    container: cypress/base:16.13.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Create env file
        shell: bash
        run: |
          touch .env
          bash ./.github/workflows/scripts/env.sh

      - name: Build
        run: yarn build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    needs: install # install job이 수행된 뒤에 cypres-run job을 실행 (job은 병렬처리가 default)
    runs-on: ubuntu-latest
    container: cypress/base:16.13.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Specify Browser since container image is compile with Firefox
          browser: firefox
          start: yarn start
