name: CI

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md
    # container: cypress/browsers:node16.5.0-chrome94-ff93
    # docker container들 다써봤는데 경로 권한 문제를 해결을 못해서 버림.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file
        env:
          REACT_APP_HOST_URL: ${{ secrets.REACT_APP_HOST_URL }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn build

      - name: Cypress run unit
        run: yarn test:unit:run

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run integration
        uses: cypress-io/github-action@v2
        with:
          # Specify Browser since container image is compile with Firefox
          browser: firefox
          start: yarn start
